# Disallowing packages: openvpn
# If you require these packages, please review the package approval process at: https://github.com/travis-ci/apt-package-whitelist#package-approval-process
#addons:
#    apt:
#        sources:
#            - ubuntu-toolchain-r-test
#        packages:
#            - openvpn

sudo: required

language: bash

env:
  global:
    - BASEIMAGE=kylemanna/openvpn
    - VERSION=latest
  matrix:
    - ARCH=amd64 FROM=alpine:latest IMAGE=$BASEIMAGE:latest-$VERSION
    - ARCH=arm FROM=multiarch/alpine:armhf-v3.7 IMAGE=$BASEIMAGE:$ARCH-$VERSION
    - ARCH=arm64 FROM=multiarch/alpine:arm64-v3.7 IMAGE=$BASEIMAGE:$ARCH-$VERSION

before_install:
    - docker --version

install:
    - git clone https://github.com/docker-library/official-images.git official-images

# Assist with ci test debugging:
#   - DEBUG=1
before_script:
    - if [ $ARCH != 'amd64' ]; then docker run --rm --privileged multiarch/qemu-user-static:register --reset; fi
    - image="$IMAGE"
    - docker build --build-arg from="$FROM" -t "$image" .
    - docker inspect "$image"
    - docker run --rm "$image" openssl version

script:
    - official-images/test/run.sh "$image"
    - test/run.sh "$image"

after_script:
    - docker images
