#!/bin/bash

QEMU_VERSION=v2.9.1-1


docker run --rm --privileged multiarch/qemu-user-static:register --reset

for i in amd64,x86_64 arm32v6,arm aarch64,aarch64; do
  IFS=","; set -- $i; 
  ARCH=$1
  QEMU_ARCH=$2

  curl -L https://github.com/multiarch/qemu-user-static/releases/download/${QEMU_VERSION}/x86_64_qemu-${QEMU_ARCH}-static.tar.gz 2>/dev/null | tar xvz 
  docker build --build-arg from="$ARCH/alpine:latest" \
               --build-arg QEMU_ARCH="$QEMU_ARCH" \
               --tag ${DOCKER_REPO}:${ARCH}-${DOCKER_TAG} .

done
